# Generated by Django 4.0 on 2021-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCommande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='DateCommande',
            field=models.CharField(max_length=20),
        ),
    ]
