# Generated by Django 4.0 on 2021-12-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('poste', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
    ]
